sudo: required
dist: xenial

services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  depth: 10

before_install:
  - source ci/travis/before-install.sh

matrix:
  fast_finish: true
  include:
    - name: "C++"
      compiler: gcc
      os: linux
      env: OS='ubuntu:16.04'
      language: cpp
      before_script:
        - docker-compose build ubuntu_cpp
      script:
        - docker-compose run ubuntu_cpp
    - name: "Centos"
      compiler: gcc
      os: linux
      language: cpp
      env: OS='centos:7'
      before_script:
        - docker-compose build centos_cpp
      script:
        - docker-compose run centos_cpp
