version: "3.5"

x-ubuntu-volumes: &ubuntu-volumes
  - .:/knn:deletaged
  - ubuntu-cache:/build:delegated

x-centos-volumes: &centos-volumes
  - ./knn:delegtaed
  - centos-cache:/build:delegated

volumes:
  ubuntu-cache:
  centos-cache:

services:
  ubuntu_cpp:
    image: knn:ubuntu_cpp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${HOME}/.ccache:/build/ccache:cached
      - .:/knn:delegated
      - ubuntu-cache:/build:delegated

  centos_cpp:
    image: knn:centos_cpp
    build:
      context: .
      dockerfile: Dockerfile.centos
    volumes:
      - .:/knn:delegated
      - centos-cache:/build:delegated
