version: "3.5"

volumes:
  ubuntu-cache:
  centos-cache:

services:
  ubuntu_cpp:
    image: knn:ubuntu_cpp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${HOME}/.ccache:/build/ccache:cached
      - .:/knn:delegated
      - ubuntu-cache:/build:delegated
      - ./dist:/build/dist:delegated

  centos_cpp:
    image: knn:centos_cpp
    build:
      context: .
      dockerfile: Dockerfile.centos
    volumes:
      - .:/knn:delegated
      - centos-cache:/build:delegated
      - ./dist:/build/dist:delegated
